### ISSUE TITLE
Flexi master branch borked while we split repos. Temporary fix inside for those depending on master

### ISSUE THREAD

**Issue by kybishop** [html-next/flexi#113]
Flexi [is being split into separate repositories](https://github.com/html-next/flexi/issues/109), likely causing issues for those depending on master.

To pin to the latest commit before splitting began, replace your flexi dependency in package.json with this line:

```
"flexi": "git://github.com/html-next/flexi.git#70f6618ec47762433d8680d8505cb88938e840dc",
```

Alternatively, help us beta test the split by removing flexi from your packages.json and reinstalling:
```
ember install --save flexi
```

[WIP] docs for 2.0.0 can be found here https://flexi.readme.io/docs/introduction

**Comment by rwwagner90** [comment]
Should be no longer broken, and people should use the latest 2.0.0 beta
