### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by michalsnik** [html-next/flexi#117]
Hey, have you considered renaming this package to `ember-flexi` in order to keep consistency  between all other ember related addons?

**Comment by rwwagner90** [comment]
@michalsnik I don't think that is necessary. What would we gain?

**Comment by michalsnik** [comment]
Nothing actually, besides consistency with general naming conventions around ember ecosystem. I was just curious :) Feel free to close this issue, I don't mind

**Comment by rwwagner90** [comment]
We'll stick with plain `flexi` for now, but will consider it.
