### ISSUE TITLE
Provide handful of example layouts

### ISSUE THREAD

**Issue by optikalefx** [html-next/flexi#119]
One of the best ways to learn, and to get started is to download seed projects, and get into the code. I may work on this myself, but I wanted to put the issue in. We should provide a few generic application layouts to get people started. Single nav left with header, Triple pane, Dashboard with portlets etc.

**Comment by rwwagner90** [comment]
@optikalefx I totally agree with you. That is in the plan. I was thinking we could tweak the current dummy app to be some interactive examples. We'd love to be able to use something like twiddle, so people could tweak them in line, but they don't support things we need to be able to do it 😞

**Comment by optikalefx** [comment]
Well when I get started on this project, I might make a few dummy layouts. We need them for work to test and play with. If I go that road, I'll share those layouts and maybe we can make an examples or starter kit folder or something.

**Comment by rwwagner90** [comment]
@optikalefx if you come up with a list of layouts you'd like to showcase, @kybishop and I could probably help you tackle implementing them. We're both interested in getting some nice examples rolling.

**Comment by optikalefx** [comment]
- My first template is going to mimic this guy http://miguelcobain.github.io/ember-paper/release-1/
- Then I'd like to do one where the navbar extends the entire top section
- The next would be the ember-paper layout but with a static footer as well as the nav
- 4th would be 2 side navs, a top nav and a body section
- last would be a 3 section layout with static header and footer.
