### ISSUE TITLE
Contibuting docs reference "develop" branch that doesn't exist

### ISSUE THREAD

**Issue by xtagon** [html-next/flexi#129]
The docs say:

```
Branch off of develop (default branch)
...
PR against develop (default branch).
```

This repo doesn't have a `develop` branch. Shall I branch off of `master`?

**Comment by runspired** [comment]
Yes

**Comment by runspired** [comment]
Fixed here: https://github.com/html-next/flexi/commit/4f384f6db648a2f88aa942d3ad4ad4ae37258acb

**Comment by xtagon** [comment]
That was fast! There were two that needed changed though

**Comment by runspired** [comment]
@xtagon fixed: https://github.com/html-next/flexi/commit/ec8d7acff976bb85bbedb4875e6f017c89c1fb89 :)
