### ISSUE TITLE
Flexi docs don't reset sizes properly, on rotating the device, on iPhone with iOS 7

### ISSUE THREAD

**Issue by marc22alain** [html-next/flexi#134]
Steps to reproduce:
- iPhone 4s with iOS 7's Safari
- open the [docs web site](https://html-next.github.io/flexi/#/docs/overview) with the device in portrait orientation
- RESULT: the page layout should properly fit the view
- rotate the device to landscape orientation
- RESULT: none of the elements adjust in size; rather, a large column of whitespace appears on the right side of the view
- rotate the device back to portrait orientation
- RESULT: now the elements do change; they expand in size and exceed the width of the view

This is evident with any page in the `html-next.github.io/flexi/#/docs/...` route.

I have performed the same exercise with an iPad Mini running iOS 10, and this behaviour is not reproduced on the iPad.

Is this an issue related to the viewport size of the smaller device, or to iOS 7 Safari version support ?

**Comment by rwwagner90** [comment]
Hi @marc22alain, that is the old docs site. I am not sure where you got that link from, but the new docs are hosted on readme.io. https://flexi.readme.io/docs

**Comment by marc22alain** [comment]
Hi @rwwagner90 , thanks for the quick response!
I found the link in the blog post: [A Tale of Two States](http://blog.isleofcode.com/modern-responsive-design/), in the first paragraph.
I am looking for examples of implementations that use Flexi, and the old docs site uses it. I see that the new site does not.
Now going off topic: I am doing some research, selecting a CSS framework for a project, and am looking for other examples of implementations. Would you know of any shining examples that show Flexi at its best?

**Comment by kybishop** [comment]
@marc22alain  http://shipshape.io and [the example site for ember-attacher](https://kybishop.github.io/ember-attacher/) are good real world examples. There are also examples in the dummy app that show how to do basic layout concepts.

**Comment by marc22alain** [comment]
@kybishop Thanks for pointing out those sites.
