### ISSUE TITLE
Flexi layouts and Emblem

### ISSUE THREAD

**Issue by mrship** [html-next/flexi#138]
We are using Emblem and would like to use Flexi Layouts. However, what we're seeing is the templates not rendering correctly, as it renders the emblem text directly into the layout.

In [this simple demo repo](https://github.com/mrship/emblem-flexi-layout) - which is just ember, emblem and flexi-layouts - we have a setup thus:

<img width="268" alt="layout" src="https://user-images.githubusercontent.com/14839/31735278-5364ffe4-b439-11e7-8f6f-b3bebec87a0a.png">

What we're seeing is a literal rendering of the emblem format.

```
= welcome-page = outlet
```

I asked on the Slack channel and @runspired suggested that this might be simple enough to fix. With the sample repo, perhaps someone could take a look and point me in the right direction, as I've not been able to get this to work as expected.

Thanks in advance for your time.

**Comment by rwwagner90** [comment]
@mrship I'm not familiar with emblem, but is it safe to use anymore? I would expect it would be tough to keep using it as Ember has transitioned from Handlebars -> HTMLBars -> Glimmer -> Glimmer 2 -> Upcoming glimmerjs based templating.

It might be best to just use the built in supported syntax Ember provides here? If that is not an option, there may be a way to get things working, but I'm not aware of it myself.

**Comment by mrship** [comment]
Emblem compiles down to handlebars and has been working fine in our app. It's basically a simpler syntax - a bit like slim vs erb in Ruby. My hope was that the emblem/handlebars compiler would run first then the layout compiler would run once it had handlebars.

@runspired suggested via Slack that:

> it’d likely be trivial to introduce emblem support to layouts, the rest of flexi not so much

Hopefully that is the case, but I'm not really sure where to start.

**Comment by rwwagner90** [comment]
@mrship I don't know much about the AST magic that happens, but we split flexi-layouts into its own repo, if you'd like to poke around https://github.com/html-next/flexi-layouts

**Comment by rwwagner90** [comment]
I do not know anything about Emblem, and we do not plan to support it, at this time, so I am closing this for now.
