### ISSUE TITLE
Blueprint should be install @html-next/flexi-config to add config file.

### ISSUE THREAD

**Issue by GCheung55** [html-next/flexi#158]
The blueprint currently doesn't install `@html-next/flexi-config`. This causes issues when a first time user is installing `flexi`. because the config file is missing but there's an error saying to generate it with a non-existant blueprint.

```
You must define a config file for flexi at '/<path-to-project>/config/flexi.js'. To generate a new config file, run `ember g @html-next/flexi-config`
```

**Comment by rwwagner90** [comment]
@GCheung55 that blueprint definitely exists here https://github.com/html-next/flexi-config/blob/master/blueprints/%40html-next/flexi-config/files/config/flexi.js

Flexi is split into a bunch of packages now, and several of them have deps on flexi-config. This worked the last time I checked.

**Comment by rwwagner90** [comment]
Since this blueprint exists, and there has been no response, I am closing the issue. If you are still experiencing issues, please let us know!
