### ISSUE TITLE
Split in various libraries

### ISSUE THREAD

**Issue by ssured** [html-next/flexi#23]
Hi,

Thanks for making this awesome software open source. I really love parts of it, but incorporating all seems too much. For example, the column css system (ported from Bootstrap?) conflicts with my choice of Curb Foundation for Apps.

Would it be an idea to split your concepts into different add ons? Like giving the sustain helper an own repo, the component-layout addon a separate home and make this an addon which combines the several parts to show its super powers? To me this cherry picking feels much more easy to port my current app to your superior code.

Kind regards,
 Sjoerd

**Comment by runspired** [comment]
Hi,

The idea is that flexi is the foundation of an explicit layout API, the specifics of your layout CSS and whether you use it's defaults shouldn't matter.  Right now, there are ways to configure this to fit into your CSS framework / grid framework of choice.  With time, this configuration story is only going to get better, easier, and more documented.

At the moment you can turn off all or parts of the CSS, or somewhat configure column names to fit your needs. (See [configuration](https://runspired.github.io/flexi/#/docs/settings) for more info.

The grid CSS was not ported from Bootstrap at all, btw, but the default configuration intentionally mimics the bootstrap class API for ease of interop for the most common case.

Version 1.2 will focus on improving the configuration and interop story.  Including exposing hooks for the attr -> class name generation, and hooks for the SASS class name generation in case you want to use Flexi's flexbox approach but keep your existing class name API.

**Comment by runspired** [comment]
You can also read the motivations behind creating Flexi to be what it is here: http://blog.isleofcode.com/modern-responsive-design/

**Comment by runspired** [comment]
I'll be leaving this issue open for discussion, but given the easy nature of configuration, and the method by which this library works, each of the scenarios you detailed above is already possible.

**Comment by ssured** [comment]
Thanks for your extensive answer. I'll dive in deeper as this library does address quite some annoyances I am having with my current responsive web app.

**Comment by runspired** [comment]
I will be splitting flexi into several micro-libs fairly soon.

Roughly:

- default-DSL
- DSL compiler
- sustain
- layouts

**Comment by kybishop** [comment]
Closing this in favor of the master issue at https://github.com/html-next/flexi/issues/109
