### ISSUE TITLE
fit/fill pre-processors not working

### ISSUE THREAD

**Issue by ksnyde** [html-next/flexi#54]
I didn't isolate this very well but ...

I was working on:

> ember `2.4.3`
> ember-cli `2.4.3`
> flexy `1.1.5` then `1.1.6`

I then upgraded `ember-cli` to `2.6.0-beta.1` and during this process I restarted the `ember serve`. I would have thought I'd have done that when I upgraded to flexi 1.1.6 too but I can't remember.

While the grid-sizing _does_ still get processed the fit/fill's no longer do. I can also add in manually the `flexi-fill` classes but that's so uncouth I shudder to think about it.

Any idea what could have created this? I tried to roll back and I'm now back to ember-cli 2.4.3 locally but maybe I need to rollback the global  install too. :(

**Comment by ksnyde** [comment]
I have rolled back `ember-cli` to 2.5.0 and then back to 2.4.3. This range doesn't have a large amount of dependency changes ... in fact the only one I can remember is `ember-ajax` which would be odd if it interfered.

I'm at a loss.

**Comment by ksnyde** [comment]
Unfortunately `1.1.7` does not fix this issue for me. :(

**Comment by ksnyde** [comment]
`1.1.7` didn't help. I feel maybe there is some other variable at play here but I'm afraid I can't shed any light on it. Any thoughts?

**Comment by ksnyde** [comment]
Ok, this is _very_ odd. I just noticed a new wrinkle. There were a number of places where I was putting `class="flexi-fill"` or `class="flexi-fit"` as the case may be and I started noticing that in many cases the post-processed HTML had duplicate entries. I tried removing these entries and low-and-behold the `fit` and `flex` properties were being translated.

In some cases but not all.

I found that in one case I had a `<box fit >` tag. Notice the space at the end? Well when I removed that space all of the preprocessing for fit and fill stopped! Put the space back in and it works.

To add to the oddity ... within the same template there is another `<box fit>` but this time it is without the space but there seems to be no complaints.

**Comment by ksnyde** [comment]
Ok, i had a sneaking suspicion that this might work ... I removed the white space mentioned above (on the troublesome `box`) but added a carriage return after the boxes markup and that too seemed to parse correctly.

Here's what it looks like now:

![2016-04-27_15-44-32](https://cloud.githubusercontent.com/assets/980757/14856237/3a8ba4c6-0c8f-11e6-9ffb-a7b8187c7e49.png)

The highlighted rectangle is the caraige return that makes the pre-processing work.

**Comment by runspired** [comment]
@ksnyde did you get any deeper into this?

**Comment by ksnyde** [comment]
@runspired I haven't got any more data points really ... in the cases where I ran into it I was able to work around it by adding the ending space and I think i've reflexively started to add this space without thinking about it so that might in part explain why I haven't run into it recently (although part of it is also me focusing a on a few addons where I'm not using flexi ... btw, how's the addon support, I'd really like to use this everywhere)

**Comment by runspired** [comment]
I've used it in a few addons, but only for docs, as well as in a few in-repo addons. Has worked thus far.

**Comment by rwwagner90** [comment]
I've had no issues with `fit` or `fill` working myself. If a reproduction can be created, we would be glad to investigate further, but I am going to close this for now.
