### ISSUE TITLE
Flexi Elements cannot contain dynamic class names.

### ISSUE THREAD

**Issue by runspired** [html-next/flexi#57]
While it's currently an intentional limitation that layout attribute usage cannot by dynamic, the same is not true for class names.

This should be possible but isn't.

```
<box xs="3" class="{{if bar 'foo' 'baz'}}">
```

**Comment by alexlafroscia** [comment]
I'm guessing that this is part of the same problem, but I discovered today that Flexi elements don't play too nicely with [`ember-css-modules`](https://github.com/salsify/ember-css-modules).

Something like this

```hbs
<box xs="12" sm="12" md="4" lg="4" class="{{styles.hero}}">
```

Adds only the CSS module class to the element; anything from Flexi is thrown away.

**Comment by runspired** [comment]
The interesting this is that there are cases in which dynamic classes are working for me.  Seems to be a function of the order of the props.  Need to nail down when this goes wrong and see what I can do.

**Comment by sammynave** [comment]
Just ran into this issue today. In case this helps anyone else, our workaround was to include the `col` classes in the mark up.
```handlebars
<box class="{{styles.radio-button-answer}} col-xs-12 col-sm-6">
```

**Comment by alexlafroscia** [comment]
I'm not sure, but I think I found another issue.

If I have a file like this in `app/application/-layout/mobile.hbs`:

```hbs
<h1 class="{{styles.foo}}">Hello, world!</h1>
```

or like this:

```hbs
<h1 local-class="foo">Hello, world!</h1>
```

I don't get the class name binding.  A static class is OK, but going through the template transformation step seems to strip out the dynamic classes, even on non-Flexi elements.

**Comment by runspired** [comment]
> going through the template transformation step seems to strip out the dynamic classes, even on non-Flexi elements

That would be a bug and a failing test is welcome. So long as a flexi class isn't being applied, dynamic classes work.  (In some cases even where they are being applied they still work, that they sometimes don't is a bug).

**Comment by alexlafroscia** [comment]
Alright, I'll put together a failing test case then to see if I can get my issue isolated.

**Comment by rwwagner90** [comment]
@alexlafroscia specifically for fixing ember-css-modules, could we enforce an `after` to enforce one addon or the other running first? https://ember-cli.com/extending/#configuring-your-ember-addon-properties

**Comment by alexlafroscia** [comment]
Hmm, that might solve the problem. Probably want to let `ember-css-modules` process the files first to turn the `local-class` into a real class name.

**Comment by rwwagner90** [comment]
@alexlafroscia do you think that change belongs in flexi or ember-css-modules?

**Comment by alexlafroscia** [comment]
I'm not sure. Not even sure that this is an issue anymore to be honest, `ember-css-modules` has changed a lot since this was reported and generally, my current app doesn't use the Flexi classes anymore.

**Comment by kybishop** [comment]
This is still an issue. I'm working on a fix and already have a rough idea of how to fix.
