### ISSUE TITLE
Document Ability to Configure Generated Column Syntax

### ISSUE THREAD

**Issue by GCheung55** [html-next/flexi#65]
Foundation 6's column syntax: 

.small-1.columns
.medium-1.columns
.large-1.columns
.[custom]-1.columns

Flexi currently follows Bootstrap column syntax.

**Comment by runspired** [comment]
@GCheung55 this is actually already supported, but the API is not documented.

**Comment by runspired** [comment]
https://github.com/runspired/flexi/blob/develop/dsl/attribute-conversion.js#L70-L79

and 

https://github.com/runspired/flexi/blob/develop/dsl/dsl-defaults.js

Are the relevant areas to look.

**Comment by rwwagner90** [comment]
Documented in the new docs https://flexi.readme.io/v1.2.0/docs/foundation
