### ISSUE TITLE
Support for 0 as an attribute value

### ISSUE THREAD

**Issue by thoov** [html-next/flexi#68]
We have a need to create a "gutter" system. Currently we are doing it like so: 

``` hbs
{{#if Flexi.isAtLeastTablet}}
  <box xs="1" sm="1" md="1" lg="1"></box>
{{/if}}
<box xs="12" sm="12" md="10" lg="10"></box>
```

This gives us a 1-10-1 layout for desktop/tablet and a 0-12-0 (full width) for mobile. However it would be simpler if we could just do this:

``` hbs
<box xs="0" sm="0" md="1" lg="1"></box>
<box xs="12" sm="12" md="10" lg="10"></box>
```

But this produces a build error as the [attribute cannot be 0](https://github.com/runspired/flexi/blob/develop/dsl/attribute-conversion.js#L9). Is there any particular reason for this restriction? And if not what are your thoughts on making this accept 0 and a valid value?

**Comment by runspired** [comment]
@thoov "theoretically" you could do this instead

```
<box xs="12" sm="10 offset-1"></box>
```

I say theoretically because if you are using flexi's default generated styles there appears to be an issue with how the offset classes are generated at the moment which I need to look into.

**Comment by runspired** [comment]
As for the comment on validity, `xs="hidden"` would be more correct, and perhaps I could alias `0` to hidden.

**Comment by thoov** [comment]
@runspired Thanks for the response. 

I didn't realize there was `offset` which is exactly what we need. The more that I think about the 0 attribute I don't actually think it is necessary.  You could simply not include the attribute which should do the same thing.

**Comment by kybishop** [comment]
Closing this out in favor of the using `hidden`. If anyone thinks there is a use-case for `0` I'll happily re-open!
