### ISSUE TITLE
img tag with src attribute in container raises error in acceptance test

### ISSUE THREAD

**Issue by HenryVonfire** [html-next/flexi#95]
I've notified @runspired  in slack but I thought that I should write the issue here. On an new empty project, having an acceptance test for a route that contains this `<container><img src="/assets/img/image.png"/></container>` in its template raises the error:

> Uncaught (in promise) EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: You have turned on testing mode,… any code with asynchronous side-effects in a run", name: "Error"…}

**Comment by HenryVonfire** [comment]
Here's a [repository example](https://github.com/HenryVonfire/img-test) of the error if it helps to solve it.

**Comment by kybishop** [comment]
Navigating to the `/register` route in the repo you provided renders the page with no errors, though testing does indeed through an error.

This leads me to believe this is a PhantomJS issue, and not directly related to Flexi.

**Comment by kybishop** [comment]
Something about that project is incorrect, but it is unrelated to Flexi. Removing flexi entirely still results in the same test error.

**Comment by HenryVonfire** [comment]
@kybishop sorry, for some reason I didn't see the resolution of this issue but I have to disagree with you. Removing the `<container>` tag makes also disappear the error, and the `<container>` tag is from flexi, so I assume it's related.

**Comment by HenryVonfire** [comment]
Since it has been a while, I've tried to recreate the project with the latest version of ember and flexi. It still happens. Here are the steps if you still think that there are something wrong in my project:

- Add an image to the path `public/assets/img/user-avatar.png` (the image really doesn't matter but having one you'll avoid the message `GET 404 not found`)
- Add a component (only the `.hbs` file if you want) with the following content:
```
<container>
<img src="/assets/img/user-avatar.png"/>
</container>
```
- Use the component in any route.
- Create an acceptance test for that route (just using `ember g acceptance-test route` is enough)
- Run `ember s` and check the dev-tools console on `localhost:4200/tests`

You'll see the error there.

- Remove `<container>` and `</container>` tags and you'll see the error disappear.

**Comment by rwwagner90** [comment]
@HenryVonfire the `img` has nothing to do with anything, I don't think. I think `container` and `grid responsive` just break the run loop in acceptance tests. I believe we are not wrapping in `run.join` for performance reasons, but it breaks testing. @runspired can you please confirm?

**Comment by kybishop** [comment]
@rwwagner90 @HenryVonfire 

From your test app:
1. remove flexi from the dependencies
2. rm -rf node_modules
3. npm install
4. ember test
5. Bug. Still. Persists.

Like I said, this doesn't have to do with flexi. If anything, this is a bug in ember-cli or ember

**Comment by kybishop** [comment]
@HenryVonfire I cannot duplicate the bug any longer with your test repo, leading me to believe this was a bug fixed in a dependency.

**Comment by HenryVonfire** [comment]
@kybishop did you test it with Firefox? it was strange for me since two days ago I tried it (even created a new project with ember 2.11 and Flexi) and the error was shown. I tried it today again and discovered that the error appears in Chrome but not in Firefox (Specifically Chrome 56.0.2924.87 (64-bit) and Firefox 51.0.1 (64-bit)).

**Comment by kybishop** [comment]
@HenryVonfire remove flexi from your packages.json, `rm -rf node_modules`, and `npm install`. If the error still happens for you, this doesn't have to do with flexi. If the error _does_ disappear, I'm open to investigating further.

**Comment by HenryVonfire** [comment]
@kybishop done. The error has disappeared.

**Comment by kybishop** [comment]
@HenryVonfire assuming we're still talking about your example repo, re-install flexi with `npm install flexi@1.2.0`, then do a full ember-cli upgrade to 2.11 https://github.com/ember-cli/ember-cli/releases/tag/v2.11.0

I'm still under the impression that this is somehow isolated to your dev environment since I can't repro on my machine. I have a hunch that an old package is cached somewhere

**Comment by HenryVonfire** [comment]
@kybishop that isn't the case because I'm in a new laptop with a different SO (from the one I had when I created the issue), a newer version of Node, Ember, Ember-cli, etc. What I did before when I said that the error disappeared was: cloning the repo, remove Flexi from `package.json`, `npm i` and `bower i` and as I said, the error was gone. But the day before yesterday I created a new project with `ember` 2.11, the latest version of `Flexi` and followed the steps I wrote [here](https://github.com/html-next/flexi/issues/95#issuecomment-278330301). And the error appeared in that new project.

**Comment by HenryVonfire** [comment]
Btw, my intention here is far from being bothering you (or anyone) with a fake issue. It's not a critical issue but I thought that you'll be interested on knowing its existence and I would love to PR a patch if I knew how to solve it, but sadly I'm not that involved in the implementation of Flexi to know how to do it.

**Comment by HenryVonfire** [comment]
@kybishop [here](https://github.com/HenryVonfire/tricky-test) is a new repo (`ember 2.11` and `flexi: 2.0.0-beta.11`). It wasn't even necessary to create the component, just placing the `<container>` tag on `application.hbs` is enough. Hope this will help in order to find the problem.

**Comment by kybishop** [comment]
@HenryVonfire 

@rwwagner90 says he has seen similar breakage from `<container>` and `<grid responsive>`, though I am still unable to reproduce:

```zsh
➜  tricky-test git:(master) ember test
cleaning up...
Built project successfully. Stored in "/Users/kybishop/github/tricky-test/tmp/core_object-tests_dist-Q4PSPEjK.tmp".
ok 1 PhantomJS 2.1 - Acceptance | application: visiting /application
ok 2 PhantomJS 2.1 - JSHint | acceptance/application-test.js: should pass jshint
ok 3 PhantomJS 2.1 - JSHint | app.js: should pass jshint
ok 4 PhantomJS 2.1 - JSHint | helpers/destroy-app.js: should pass jshint
ok 5 PhantomJS 2.1 - JSHint | helpers/module-for-acceptance.js: should pass jshint
ok 6 PhantomJS 2.1 - JSHint | helpers/resolver.js: should pass jshint
ok 7 PhantomJS 2.1 - JSHint | helpers/start-app.js: should pass jshint
ok 8 PhantomJS 2.1 - JSHint | resolver.js: should pass jshint
ok 9 PhantomJS 2.1 - JSHint | router.js: should pass jshint
ok 10 PhantomJS 2.1 - JSHint | test-helper.js: should pass jshint

1..10
# tests 10
# pass  10
# skip  0
# fail  0

# ok
```

Going to re-open this and assign to RWW since he mentioned looking into it. A bit hard for me without being able to repro ;)

**Comment by HenryVonfire** [comment]
Problem solved with with this [PR](https://github.com/html-next/flexi-layouts/pull/3).

Thanks for your time guys!

**Comment by kybishop** [comment]
Thanks for your persistence @HenryVonfire!
